- name: Add Elastic GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Elastic APT repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    filename: elastic-7.x
  when: ansible_os_family == "Debian"

- name: Update apt package index
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Logstash
  apt:
   name: logstash
   state: present
  when: ansible_os_family == "Debian"

- name: Start and enable Logstash service
  service:
   name: logstash
   state: started
   enabled: yes
