- name: Install necessary packages
  apt:
    name:
      - apt-transport-https
      - curl
      - gnupg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Elasticsearch GPG key (Debian)
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_os_family == "Debian"

- name: Add Elasticsearch repository (Debian)
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
  when: ansible_os_family == "Debian"

- name: Install Elasticsearch (Debian)
  apt:
    name: elasticsearch
    state: present
  when: ansible_os_family == "Debian"

- name: Install necessary packages (CentOS)
  yum:
    name:
      - libcurl
      - wget
      - epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Elasticsearch GPG key (CentOS)
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_os_family == "RedHat"

- name: Add Elasticsearch repository (CentOS)
  yum_repository:
    name: elasticsearch-8.x
    description: ElasticSearch repository
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    gpgcheck: yes
    enabled: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_os_family == "RedHat"

- name: Install Elasticsearch (CentOS)
  yum:
    name: elasticsearch
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable Elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install Logstash (Ubuntu)
  apt:
    name: logstash
    state: present
  when: ansible_os_family == "Debian"

- name: Install Logstash (CentOS)
  yum:
    name: logstash
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Kibana (Ubuntu)
  apt:
    name: kibana
    state: present
  when: ansible_os_family == "Debian"

- name: Install Kibana (CentOS)
  yum:
    name: kibana
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable Kibana service
  service:
    name: kibana
    state: started
    enabled: yes

- name: Start and enable Logstash service
  service:
    name: logstash
    state: started
    enabled: yes

- name: Configure Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify:
    - restart kibana

